[seaweed-nodes]
seaweedfs-node ansible_host=143.244.201.207 ansible_user=fnadmin ansible_ssh_private_key_file=~/.ssh/id_ed25519

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'