---
- name: "Configuração da Infraestrutura de Dados"
  hosts: all
  become: yes
  roles:
    - role: common
      tags: common

- name: "Configuração do PostgreSQL"
  hosts: seaweed-nodes
  become: yes
  roles:
    - role: postgres
      tags: postgres
  post_tasks:
    - name: "Forçar execução dos handlers pendentes"
      meta: flush_handlers

    - name: "Aguardar PostgreSQL aceitar conexões externas"
      wait_for:
        host: "192.168.56.101"
        port: 5432
        delay: 3
        timeout: 30

- name: "Configuração do SeaweedFS"
  hosts: seaweed-nodes
  become: yes
  roles:
    - role: seaweed
      tags: seaweed
  post_tasks:
    - name: "Forçar execução dos handlers pendentes"
      meta: flush_handlers
    - name: "Aguardar SeaweedFS S3 Gateway aceitar conexões"
      wait_for:
        host: "192.168.56.101"
        port: 8333
        delay: 3
        timeout: 30

- name: "Configuração do Open Policy Agent (OPA)"
  hosts: seaweed-nodes
  become: yes
  roles:
    - role: opa
      tags: [opa, governance]
  post_tasks:
    - name: "Forçar execução dos handlers pendentes"
      meta: flush_handlers
    - name: "Aguardar OPA aceitar conexões"
      wait_for:
        host: "192.168.56.101"
        port: 8282
        delay: 3
        timeout: 30

- name: "Configuração do Polaris"
  hosts: seaweed-nodes
  become: yes
  roles:
    - role: polaris
      tags: polaris