---
# ==============================================================================
# USUÁRIO E DIRETÓRIOS
# ==============================================================================
opa_user: opa
opa_group: opa
opa_install_dir: /opt/opa
opa_data_dir: /data/opa
opa_log_dir: /var/log/opa
opa_conf_dir: /etc/opa
opa_policies_dir: /etc/opa/policies

# ==============================================================================
# BINÁRIO E VERSÃO
# ==============================================================================
opa_version: "1.17.1"
opa_binary_name: opa

# ==============================================================================
# SERVIÇO
# ==============================================================================
opa_port: 8282
opa_addr: "0.0.0.0"
opa_log_level: "info"
opa_log_format: "json"

# ==============================================================================
# SEGURANÇA (futuro: TLS, auth)
# ==============================================================================
opa_enable_tls: false
opa_tls_cert: ""
opa_tls_key: ""

# ==============================================================================
# BUNDLES (futuro: políticas remotas)
# ==============================================================================
opa_enable_bundles: false
opa_bundle_service_url: ""

# ==============================================================================
# BUNDLES (políticas distribuídas via SeaweedFS Filer)
# ==============================================================================
opa_enable_bundles: true
opa_bundle_service_url: "http://192.168.56.101:8888"
opa_bundle_resource: "/buckets/opa-policies/bundle.tar.gz"
opa_bundle_polling_min: 10
opa_bundle_polling_max: 30